# Generated by Django 5.0.4 on 2024-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeddata',
            name='site_name',
            field=models.CharField(default='', max_length=100, verbose_name='site_name'),
        ),
        migrations.AlterField(
            model_name='mergeddata',
            name='root_cause',
            field=models.CharField(max_length=100, verbose_name='root_cause'),
        ),
    ]
