# Generated by Django 5.0.4 on 2024-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
